package mil.nga.elevation;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.3.1
 * 2019-04-24T10:08:04.710-05:00
 * Generated source version: 3.3.1
 *
 */
@WebService(targetNamespace = "mil:nga:elevation", name = "Elevation")
@XmlSeeAlso({us.gov.ic.ism.v2.ObjectFactory.class, mil.nga.security.ObjectFactory.class, ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface Elevation {

    @WebMethod
    @WebResult(name = "GetElevationAtResponse", targetNamespace = "mil:nga:elevation", partName = "result")
    public GetElevationAtResponse getElevationAt(
        @WebParam(partName = "parameters", name = "GetElevationAt", targetNamespace = "mil:nga:elevation")
        GetElevationAt parameters
    );

    @WebMethod
    @WebResult(name = "GetMinMaxElevationsResponse", targetNamespace = "mil:nga:elevation", partName = "result")
    public GetMinMaxElevationsResponse getMinMaxElevations(
        @WebParam(partName = "parameters", name = "GetMinMaxElevations", targetNamespace = "mil:nga:elevation")
        GetMinMaxElevations parameters
    );

    @WebMethod
    @WebResult(name = "GetMinMaxElevationsWKTResponse", targetNamespace = "mil:nga:elevation", partName = "result")
    public GetMinMaxElevationsWKTResponse getMinMaxElevationsWKT(
        @WebParam(partName = "parameters", name = "GetMinMaxElevationsWKT", targetNamespace = "mil:nga:elevation")
        GetMinMaxElevationsWKT parameters
    );
}
