package mil.nga.elevation;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.1
 * 2019-04-24T10:08:04.732-05:00
 * Generated source version: 3.3.1
 *
 */
@WebServiceClient(name = "elevation_service",
                  wsdlLocation = "WEB-INF/wsdl/elevation_service.wsdl",
                  targetNamespace = "mil:nga:elevation")
public class ElevationService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("mil:nga:elevation", "elevation_service");
    public final static QName ElevationServicePort = new QName("mil:nga:elevation", "ElevationServicePort");
    static {
        URL url = ElevationService.class.getResource("WEB-INF/wsdl/elevation_service.wsdl");
        if (url == null) {
            url = ElevationService.class.getClassLoader().getResource("WEB-INF/wsdl/elevation_service.wsdl");
        }
        if (url == null) {
            java.util.logging.Logger.getLogger(ElevationService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "WEB-INF/wsdl/elevation_service.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ElevationService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ElevationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ElevationService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ElevationService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ElevationService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ElevationService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns Elevation
     */
    @WebEndpoint(name = "ElevationServicePort")
    public Elevation getElevationServicePort() {
        return super.getPort(ElevationServicePort, Elevation.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Elevation
     */
    @WebEndpoint(name = "ElevationServicePort")
    public Elevation getElevationServicePort(WebServiceFeature... features) {
        return super.getPort(ElevationServicePort, Elevation.class, features);
    }

}
